// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGC6iZK3AQ4YpHcYxgBrbG8fvwaQ8jCSQ',
    appId: '1:859764461744:web:df0eac31145b42e1916b75',
    messagingSenderId: '859764461744',
    projectId: 'trackingapptest-b7d7d',
    authDomain: 'trackingapptest-b7d7d.firebaseapp.com',
    storageBucket: 'trackingapptest-b7d7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSZzOZ5bYmRKD9RSaf7IA8YEC-33uytxw',
    appId: '1:859764461744:android:6f1afe10b60200ce916b75',
    messagingSenderId: '859764461744',
    projectId: 'trackingapptest-b7d7d',
    storageBucket: 'trackingapptest-b7d7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpdS7IHl8_PmeSwYIq3HqOBo8LTZHPHag',
    appId: '1:859764461744:ios:8f298d36c5e135f3916b75',
    messagingSenderId: '859764461744',
    projectId: 'trackingapptest-b7d7d',
    storageBucket: 'trackingapptest-b7d7d.firebasestorage.app',
    iosBundleId: 'com.example.trackingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpdS7IHl8_PmeSwYIq3HqOBo8LTZHPHag',
    appId: '1:859764461744:ios:8f298d36c5e135f3916b75',
    messagingSenderId: '859764461744',
    projectId: 'trackingapptest-b7d7d',
    storageBucket: 'trackingapptest-b7d7d.firebasestorage.app',
    iosBundleId: 'com.example.trackingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGC6iZK3AQ4YpHcYxgBrbG8fvwaQ8jCSQ',
    appId: '1:859764461744:web:b6d803b9fb8ca563916b75',
    messagingSenderId: '859764461744',
    projectId: 'trackingapptest-b7d7d',
    authDomain: 'trackingapptest-b7d7d.firebaseapp.com',
    storageBucket: 'trackingapptest-b7d7d.firebasestorage.app',
  );
}
